// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnivhjxysfdbmnatvttv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduaXZoanh5c2ZkYm1uYXR2dHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDM5NjksImV4cCI6MjA2Njg3OTk2OX0.VAihaC70K4gunlkVn5Qx-_OIMgnNptWM0bwhmPQ2LEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});